### ISSUE TITLE
The model: `gpt-4` and `gpt-4-32k` does not exist.

### ISSUE THREAD

**Issue by evanclue** [evilpan/gptcli#10]
I made absolutely sure my local directory was updated to the latest version. I have GPT Pro, and it works fine with `gpt-3.5-turbo`, but when the config is set to `gpt-4` or `gpt-4-32k`, it says the model does not exist.

![ubuntu_ePHMr7WdTk](https://user-images.githubusercontent.com/72628412/225786755-87aa5ea6-bac9-46a4-bc87-2e5deead6aa5.png)

**Comment by evilpan** [comment]
Currently the `gpt-4` model is in [limited beta](https://platform.openai.com/docs/models/gpt-4), and you may need to join the waitlist to get access when capacity is available.
