### ISSUE TITLE
使用.save 保存到文件时，中文乱码

### ISSUE THREAD

**Issue by leiping520** [evilpan/gptcli#15]
![image](https://user-images.githubusercontent.com/39257165/227689838-58b75f60-f588-46ba-8cfd-3d239e99ebc8.png)

**Comment by evilpan** [comment]
fixed in https://github.com/evilpan/gptcli/commit/579fa98281852dd761d09167825a48cec9f9d3a0

现在默认统一编码为 UTF-8 存储，如果仍然有乱码问题，`.save` 和 `.load` 命令可以支持自定义 encoding，如 `-e gbk/utf8`，可根据需要自行选择。
