### ISSUE TITLE
Answer with panic

### ISSUE THREAD

**Issue by VegeBun-csj** [evilpan/gptcli#16]
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/39252213/227785519-2cc31662-4c14-4735-b25e-8c6947efef5e.png">

**Comment by evilpan** [comment]
This usually indicates that the API server terminates the current connection for some reason, which could be ignored and a simple resend would be fine. However if it occurs frequently, I'll try to handle this issue more gracefully.

**Comment by VegeBun-csj** [comment]
Thanks
