### ISSUE TITLE
如何在容器内配置宿主机的代理地址，现在配置还是报错

### ISSUE THREAD

**Issue by leiping520** [evilpan/gptcli#18]
![image](https://user-images.githubusercontent.com/39257165/227974531-b0108749-5b9a-4700-94be-ad33309a2777.png)

**Comment by leiping520** [comment]
> 127.0.0.1? Does the proxy run on this host?

yes,but not run

**Comment by evilpan** [comment]
Just start docker with `--network host`

**Comment by leiping520** [comment]
> Just start docker with `--network host`
![image](https://user-images.githubusercontent.com/39257165/228272252-4100d663-bedd-4beb-96dd-5766012bee59.png)
not work，but i set proxy of my telegram that run it.

**Comment by evilpan** [comment]
You may need some googlefu for those docker related questions, e.x. https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach
