### ISSUE TITLE
cannot import name 'MarkdownIt' from 'rich.markdown'

### ISSUE THREAD

**Issue by leolle** [evilpan/gptcli#7]
Hello, 我是windows 10, python 3.7.8.

Traceback (most recent call last):
  File "gptcli.py", line 10, in <module>
    from rich.markdown import Markdown, MarkdownIt
ImportError: cannot import name 'MarkdownIt' from 'rich.markdown'

**Comment by evilpan** [comment]
Could you please try updating `rich` module?

```sh
python3 -m pip install -U rich
```

**Comment by leolle** [comment]
Thank you.
