### ISSUE TITLE
response displayed word by word, line by line.

### ISSUE THREAD

**Issue by leolle** [evilpan/gptcli#8]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/12882642/225218313-c8c797ce-80fe-4103-9739-641f68623b11.png">

**Comment by evilpan** [comment]
Sorry but I can't reproduce this issue, which termial app are you running on?

**Comment by leolle** [comment]
windows cmd.

**Comment by evilpan** [comment]
I've tested on both cmd.exe and Windows Terminal, and it works well.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/4104311/225300224-f9f8a85d-a8c6-4853-87d5-1084fd03cfd7.png">

Maybe you could try another question, or update your system prompt in `config.json`

**Comment by t812206236** [comment]
I ran into this problem too, when I asked it a question and it started giving me code in markdown format, and the first sentence started repeating itself over and over again. I use the windows version of python
![屏幕截图 2023-03-16 084909](https://user-images.githubusercontent.com/13000267/225481615-a027e596-5bbe-41ee-a766-17e69642ff2f.png)

**Comment by evilpan** [comment]
这可能是一个中文输入/输出的潜在问题，但我在 Windows10/Windows11 中无法复现，可能需要更多的信息:

1. 这种情况是在什么版本的 Windows 系统中出现？
2. 是否对于每个请求都会出现？可以稳定复现吗？
3. 可否将 `config.json` 中的 `prompt` 设置为空 `"prompt": []` 再进行测试？

**Comment by evilpan** [comment]
`gptcli.py` 经过了多个版本的升级和优化，现在是否还存在上述情况呢？如果没有更多反馈，该问题将会在近期进行合并。

**Comment by t812206236** [comment]
收到，我测试一下

**Comment by t812206236** [comment]
@evilpan 还是会存在问题。更多信息：
1. windows10专业版 版本号21H2
2. 没办法稳定复现，不过出现频率挺高，你日常使用一天能遇到好几次
3. prompt清空我再试下

**Comment by t812206236** [comment]
@evilpan 我知道怎么稳定复现了，只要它回的答案是带有数字序号的就很大概率出现，比如说
1. xxx
2. xxx
3. xxx
4. ...

**Comment by leiping520** [comment]
> @evilpan 我知道怎么稳定复现了，只要它回的答案是带有数字序号的就很大概率出现，比如说
> 
> 1. xxx
> 2. xxx
> 3. xxx
> 4. ...

这个解决了吗

**Comment by leiping520** [comment]
> `gptcli.py` 经过了多个版本的升级和优化，现在是否还存在上述情况呢？如果没有更多反馈，该问题将会在近期进行合并。
![image](https://user-images.githubusercontent.com/39257165/228104387-d0f9872b-783e-4696-b77b-29b7eda8b08f.png)

这问题经常出现

**Comment by evilpan** [comment]
@leiping520 Windows 版本和 Terminal 版本是什么呢？也是 `cmd.exe` 吗？

**Comment by evilpan** [comment]
抱歉，不过目前我的常用环境中都没有成功复现过这个问题，测试的环境为:

- Windows 11 + cmd.exe
- Windows 11 + Windows Terminal
- Windows 11 + Windows Powershell
- Windows Server 2022 + cmd.exe
- Windows Server 2022 + Windows Terminal
- Windows Server 2022 + Windows Powershell

希望能有更多信息以便后续我安装对应虚拟机去进行复现。

**Comment by t812206236** [comment]
@evilpan 你用我电脑调试吧，qq远程协助 812206236

**Comment by evilpan** [comment]
Hi all,

我更新了一下代码，主要增加一个 `stream_render` 的配置选项，表示是否在流式模式中实时渲染 Markdown，仅在流式输出结束时进行一次性渲染。看一下将其设置为 false 能否解决这个 bug？

**Comment by t812206236** [comment]
@evilpan 
![1](https://user-images.githubusercontent.com/13000267/228152893-9dff2f3c-1433-4355-85b0-b7833efa9c0b.png)
左边这个是stream_render为false的情况，右边这个是为true时的情况，我问的问题是：“proe导出时的弦高和角度控制”，几乎100%复现，我观察了出错的原因，大概就是在数字序号出现的时候，且每个序号内容超出屏幕要换行的时候就容易出现，如果每行的内容在命令行宽度范围以内就不会出现。

- 我问chatgpt这种问题出现的原因，回答我说rich.console的自动换行可能会引起这个问题，修改成不自动换行，没有效果
- chatgpt说也有可能和rich.live的自动刷新有关，打开true就行，尝试也无用

如果其他平台没问题那就不用管了吧，可能就是win10这版有问题？
